document.writeln("<div class=\'footer\'>");
document.writeln("        <div class=\'wrapper\'>");
document.writeln("            <div class=\'top\'>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>指导单位</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>浙江省互联网信息办公室</li>");
document.writeln("                        <li>浙江省经济和信息化厅</li>");
document.writeln("                        <li>浙江省公安厅</li>");
document.writeln("                        <li>浙江省发展和改革委员会</li>");
document.writeln("                        <li>浙江省通信管理局</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>主办单位</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>杭州市人民政府</li>");
document.writeln("");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>联合主办单位</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>中国信息通信研究院</li>");
document.writeln("                        <li>中国网络空间研究院</li>");
document.writeln("                        <li>国家工业信息安全发展研究中心</li>");
document.writeln("                        <li>中国电子技术标准化研究院</li>");
document.writeln("                        <li>工业和信息化部教育与考试中心</li>");
document.writeln("                        <li>杭州市滨江区人民政府</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>承办单位</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>杭州市互联网信息办公室</li>");
document.writeln("                        <li>杭州市经济和信息化局</li>");
document.writeln("                        <li>杭州市公安局</li>");
document.writeln("                        <li>杭州市发展和改革委员会</li>");
document.writeln("                        <li>浙江省网络空间安全协会</li>");
document.writeln("                        <li>安恒信息</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'middle\'>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>战略合作媒体</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>新华网</li>");
document.writeln("");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class=\'row\'>");
document.writeln("                    <h1>特别支持媒体</h1>");
document.writeln("                    <ul>");
document.writeln("                        <li>光明网</li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'bottom\'>");
document.writeln("                <div class=\'left\'>");
document.writeln("                    <img src=\'../index/images/logo_bottom.png\' alt=\'\'>");
document.writeln("                    <h1>隐私条款 / 服务条款</h1>");
document.writeln("                    <h1>技术支持：代码写的都很队</h1>");
document.writeln("                </div>");
document.writeln("                <div class=\'middle\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a href=\'../index/index.html\'>首页</a></li>");
document.writeln("                        <li><a href=\'../agenda/agenda.html\'>大会议程</a></li>");
document.writeln("                        <li><a href=\'\'>关于大会</a></li>");
document.writeln("                        <li><a href=\'\'>大咖云集</a></li>");
document.writeln("                        <li><a href=\'\'>精彩活动</a></li>");
document.writeln("                        <li><a href=\'\'>展商风采</a></li>");
document.writeln("                        <li><a href=\'../result/result.html\'>成果发布</a></li>");
document.writeln("                        <li><a href=\'../media/media.html\'>媒体中心</a></li>");
document.writeln("                        <li><a href=\'../guide/guide.html\'>参会指南</a></li>");
document.writeln("                        <li><a href=\'../live/live.html\'>大会直播</a></li>");
document.writeln("                    </ul>");
document.writeln("");
document.writeln("                </div>");
document.writeln("");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");