document.writeln("<div class=\'header\'>");
document.writeln("        <div class=\'wrapper\'>");
document.writeln("            <div class=\'logo\'>");
document.writeln("                <a href=\'\'><img src=\'../images/head/logo.png\' alt=\'\'></a>");
document.writeln("            </div>");
document.writeln("            <div class=\'nav\'>");
document.writeln("                <ul>");
document.writeln("                    <li><a id=\'index\' href=\'../index/index.html\'>首页</a></li>");
document.writeln("                    <li><a id=\'agenda\' href=\'../agenda/agenda.html\'>大会议程</a></li>");
document.writeln("                    <li><a id=\'speaker\' href=\'../speaker/speaker.html\'>关于大会</a></li>");
document.writeln("                    <li><a id=\'guest\' href=\'../guest/guest.html\'>大咖云集</a></li>");
document.writeln("                    <li><a id=\'activity\' href=\'../activity/activity.html\'>精彩活动</a></li>");
document.writeln("                    <li><a id=\'exhibit\' href=\'../exhibit/exhibit.html\'>展商风采</a></li>");
document.writeln("                    <li><a id=\'result\' href=\'../result/result.html\'>成果发布</a></li>");
document.writeln("                    <li><a id=\'media\' href=\'../media/media.html\'>媒体中心</a></li>");
document.writeln("                    <li><a id=\'guide\' href=\'../guide/guide.html\'>参会指南</a></li>");
document.writeln("                    <li><a class=\'live\' href=\'../live/live.html\'>大会直播</a>");
document.writeln("                        <img src=\'../images/head/icon_live.png\' alt=\'\'>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'user\'>");
document.writeln("            <span class=\'iconfont icon-yonghu\'><a href=\'../user/user.html\'>个人中心</a></span>");
document.writeln("            <span><a href=\'../index.html\'>退出</a></span>");
document.writeln("        </div>");
document.writeln("    </div>");